import type { SiteSettings } from "@/types";

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  agencyName: "AGMERZ ESTATE",
  description: "Премиальное агентство недвижимости в Грозном",
  phone: "+7 (928) 888-88-88",
  whatsapp: "+79288888888",
  email: "info@agmerz.ru",
  address: "Грозный, Чеченская Республика",
  city: "Грозный",
  workingHours: "Пн — Пт: 09:00 — 19:00, Сб: 10:00 — 17:00, Вс: выходной",
  instagram: "https://instagram.com",
  telegram: "",
  tiktok: "",
  facebook: "",
  siteTitle: "AGMERZ ESTATE — Недвижимость в Грозном",
  metaTitle: "AGMERZ ESTATE — Недвижимость в Грозном",
  metaDescription: "Премиальное агентство недвижимости в Грозном. Квартиры, дома, коммерция, аренда.",
  ogImage: "",
  googleAnalyticsId: "",
  language: "ru",
  currency: "₸",
  contactPhone: "+7 (928) 888-88-88",
  contactEmail: "info@agmerz.ru",
  contactWhatsapp: "+79288888888",
  contactAddress: "Грозный, Чеченская Республика",
  googleMapsUrl: "https://yandex.ru/maps/?text=Grozny",
  leadEmail: "info@agmerz.ru",
  leadWhatsapp: "+79288888888",
  notificationsEnabled: true,
  defaultRequestStatus: "new",
  logoUrl: "/images/agmerz-estate-logo.png",
  faviconUrl: "",
};
